-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 15:12:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estacionamento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `estacionamento`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionamento`.`valores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valores` (
  `id` INT NOT NULL,
  `valor_hora` FLOAT NULL,
  `valor_dia` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets` (
  `id` INT NOT NULL,
  `data_entrada` DATETIME NOT NULL,
  `data_saida` DATETIME NULL,
  `placa` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  `valores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_usuario_idx` (`usuario_id` ASC),
  INDEX `fk_tickets_valores1_idx` (`valores_id` ASC),
  CONSTRAINT `fk_tickets_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_valores1`
    FOREIGN KEY (`valores_id`)
    REFERENCES `valores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionamento`.`vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vagas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quant_vagas` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

ALTER TABLE `tickets` 
DROP FOREIGN KEY `fk_tickets_valores1`,
DROP FOREIGN KEY `fk_tickets_usuario`;
ALTER TABLE `estacionamento`.`tickets` 
DROP COLUMN `usuario_id`,
ADD COLUMN `nome_prop` VARCHAR(45) NULL AFTER `valores_id`,
ADD COLUMN `telefone_prop` VARCHAR(45) NULL AFTER `nome_prop`,
CHANGE COLUMN `valores_id` `valores_id` INT(11) NULL ,
DROP INDEX `fk_tickets_usuario_idx` ;
;
ALTER TABLE `estacionamento`.`tickets` 
ADD CONSTRAINT `fk_tickets_valores1`
  FOREIGN KEY (`valores_id`)
  REFERENCES `valores` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
  ALTER TABLE `tickets` 
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
